baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en_US"
  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de_DE"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@skymatic/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

  [[module.mounts]]
    source = "node_modules/js-yaml/dist"
    target = "assets/js/js-yaml"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.13.0"
      filename = "Cryptomator-1.13.0-x64.exe"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-x64.exe"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-x64.exe.asc"
      checksum = "30f3bd01a54098402b86a67c720c27550fabe09b931ff635fdc397936fa56984"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.msi]
      version = "1.13.0"
      filename = "Cryptomator-1.13.0-x64.msi"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-x64.msi"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-x64.msi.asc"
      checksum = "e077c0b0e08cc9bec27ca6990281efc9f361f11b88f80ccf73201dded6af6c98"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.dmg]
      version = "1.13.0"
      filename = "Cryptomator-1.13.0.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-x64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-x64.dmg.asc"
      checksum = "0ee9bf21b9b299a814d702281c9778d69de18fc862ca3b1a905546fd414df9d7"
      requiredOS = 'macOS 11'
    [params.releases.dmg-arm64]
      version = "1.13.0"
      filename = "Cryptomator-1.13.0-arm64.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-arm64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/Cryptomator-1.13.0-arm64.dmg.asc"
      checksum = "6114e47e8fba33f1518ab45a87c53614a988e29cf9cd2f8ccbbc6ef523111c72"
      requiredOS = 'macOS 11'
    [params.releases.appimage]
      version = "1.13.0"
      filename = "cryptomator-1.13.0-x86_64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/cryptomator-1.13.0-x86_64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/cryptomator-1.13.0-x86_64.AppImage.asc"
      checksum = "926cc4f0ec45f4669989ab28fedbd9c2bbb9e2e1d5c5d534e893f5fb3998a20e"
      requiredOS = ''
    [params.releases.appimage-aarch64]
      version = "1.13.0"
      filename = "cryptomator-1.13.0-aarch64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/cryptomator-1.13.0-aarch64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.13.0/cryptomator-1.13.0-aarch64.AppImage.asc"
      checksum = "7095f5dbabc0e1d40a4becc829f9c0705cb22188c86717589574fde7842cccde"
      requiredOS = ''
    [params.releases.android]
      version = "1.10.2"
      filename = "Cryptomator-1.10.2.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.10.2/Cryptomator-1.10.2.apk"
      checksum = "7ac9fadd5da11740732fae34652e19f1cd31450dc2eb4b55ddfb9e52fd8be151"
      requiredOS = 'Android 8.0'

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
