# set to true in frontmatter if required
math: false

anniversaryBanner:
  enabled: true
  excludePaths:
    - /downloads-thanks/
    - /paddle-checkout/
    - /hub/billing/

releases:
  exe:
    version: 1.19.1
    filename: Cryptomator-1.19.1-x64.exe
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-x64.exe
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-x64.exe.asc
    checksum: 08beab0e625339aa8525339388a1317987dc0f2f70d114737cbaf66d0ce62a1a
    requiredOS: Windows 10, Version 1803
  msi:
    version: 1.19.1
    filename: Cryptomator-1.19.1-x64.msi
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-x64.msi
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-x64.msi.asc
    checksum: 77ff121b725938bc05efaa842cfd7db2bbe0f32ca76c93b98c65b225d226d7fd
    requiredOS: Windows 10, Version 1803
  dmg:
    version: 1.19.1
    filename: Cryptomator-1.19.1.dmg
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-x64.dmg
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-x64.dmg.asc
    checksum: 14e3273f02268c6abf9a9962dbf35a01f45f4dd75ea90973af3827fcf88b96cb
    requiredOS: macOS 11
  dmg-arm64:
    version: 1.19.1
    filename: Cryptomator-1.19.1-arm64.dmg
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-arm64.dmg
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/Cryptomator-1.19.1-arm64.dmg.asc
    checksum: c208184d36b1570e00c2929b3b230679191235742385e883863135ee67e9c581
    requiredOS: macOS 11
  appimage:
    version: 1.19.1
    filename: cryptomator-1.19.1-x86_64.AppImage
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/cryptomator-1.19.1-x86_64.AppImage
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/cryptomator-1.19.1-x86_64.AppImage.asc
    checksum: 6acfccb9368731a96c375a1ec26666c93fd5735c03d200b9bf37d6e290a18116
    requiredOS: ""
  appimage-aarch64:
    version: 1.19.1
    filename: cryptomator-1.19.1-aarch64.AppImage
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/cryptomator-1.19.1-aarch64.AppImage
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.1/cryptomator-1.19.1-aarch64.AppImage.asc
    checksum: 05af34b8c6430d4e033f029eb20071ec718e529715f15e41f91230665d146849
    requiredOS: ""
  android:
    version: 1.11.1
    filename: Cryptomator-1.11.1.apk
    downloadUrl: https://static.cryptomator.org/android/1.11.1/Cryptomator-1.11.1.apk
    checksum: cd779e929277920e65b282f166e9c693fe560927215428796e100bcc7427132a
    requiredOS: Android 8.0
