math = false # set to true in frontmatter if required

[releases]
  [releases.exe]
    version = "1.17.1"
    filename = "Cryptomator-1.17.1-x64.exe"
    downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-x64.exe"
    signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-x64.exe.asc"
    checksum = "a11dfcfc5bb9b032448292755a2229bb6cc181f4978864f8f4f0df626c4e6e69"
    requiredOS = 'Windows 10, Version 1803'
  [releases.msi]
    version = "1.17.1"
    filename = "Cryptomator-1.17.1-x64.msi"
    downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-x64.msi"
    signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-x64.msi.asc"
    checksum = "794435f090232a8af2d0e9fb770e02ce2d99326323433a46f4125cefb3e6713b"
    requiredOS = 'Windows 10, Version 1803'
  [releases.dmg]
    version = "1.17.1"
    filename = "Cryptomator-1.17.1.dmg"
    downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-x64.dmg"
    signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-x64.dmg.asc"
    checksum = "0111ad60e0a9749a63f11eb4eae183aaf05ceb6dde67b8c28bcc8b2447b86850"
    requiredOS = 'macOS 11'
  [releases.dmg-arm64]
    version = "1.17.1"
    filename = "Cryptomator-1.17.1-arm64.dmg"
    downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-arm64.dmg"
    signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/Cryptomator-1.17.1-arm64.dmg.asc"
    checksum = "34c75e5f744bcedb96cf900a7e73ae96a5b39568a2e0994a1239fc59b31bc0d5"
    requiredOS = 'macOS 11'
  [releases.appimage]
    version = "1.17.1"
    filename = "cryptomator-1.17.1-x86_64.AppImage"
    downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/cryptomator-1.17.1-x86_64.AppImage"
    signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/cryptomator-1.17.1-x86_64.AppImage.asc"
    checksum = "290d30f81535483d01f1a799d380c90c2a194a0b6151418ac636f0f015d0372a"
    requiredOS = ''
  [releases.appimage-aarch64]
    version = "1.17.1"
    filename = "cryptomator-1.17.1-aarch64.AppImage"
    downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/cryptomator-1.17.1-aarch64.AppImage"
    signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.17.1/cryptomator-1.17.1-aarch64.AppImage.asc"
    checksum = "5bb552c3f801c0007c5dc5c2a7e9e29eaf2ec0c28e5dca1d5e52c473905fba2f"
    requiredOS = ''
  [releases.android]
    version = "1.11.1"
    filename = "Cryptomator-1.11.1.apk"
    downloadUrl = "https://static.cryptomator.org/android/1.11.1/Cryptomator-1.11.1.apk"
    checksum = "cd779e929277920e65b282f166e9c693fe560927215428796e100bcc7427132a"
    requiredOS = 'Android 8.0'