# set to true in frontmatter if required
math: false

anniversaryBanner:
  enabled: true
  excludePaths:
    - /downloads-thanks/
    - /paddle-checkout/
    - /hub/billing/

releases:
  exe:
    version: 1.19.0
    filename: Cryptomator-1.19.0-x64.exe
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-x64.exe
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-x64.exe.asc
    checksum: 5cd1701a56ee197325a24611908b00064fa4552903ab34756189ddf687007428
    requiredOS: Windows 10, Version 1803
  msi:
    version: 1.19.0
    filename: Cryptomator-1.19.0-x64.msi
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-x64.msi
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-x64.msi.asc
    checksum: 48f0906ffdcd89c802299a49fdfbe63d367c308dc34879efd3d14c634111cea5
    requiredOS: Windows 10, Version 1803
  dmg:
    version: 1.19.0
    filename: Cryptomator-1.19.0.dmg
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-x64.dmg
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-x64.dmg.asc
    checksum: 3ba6011fe50574ee356c0e0f1a869afdd48f3e8059a679175ae8cb87c965475d
    requiredOS: macOS 11
  dmg-arm64:
    version: 1.19.0
    filename: Cryptomator-1.19.0-arm64.dmg
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-arm64.dmg
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/Cryptomator-1.19.0-arm64.dmg.asc
    checksum: f4cc20ba7b8befa8deed0f6fc495e39843228e8dbe48c7314e8fa0b06ad6a162
    requiredOS: macOS 11
  appimage:
    version: 1.19.0
    filename: cryptomator-1.19.0-x86_64.AppImage
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/cryptomator-1.19.0-x86_64.AppImage
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/cryptomator-1.19.0-x86_64.AppImage.asc
    checksum: 42bb500d5257f34a2ee220ada58ab49c28861492dd22183fb77c692ba39f11e6
    requiredOS: ""
  appimage-aarch64:
    version: 1.19.0
    filename: cryptomator-1.19.0-aarch64.AppImage
    downloadUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/cryptomator-1.19.0-aarch64.AppImage
    signatureUrl: https://github.com/cryptomator/cryptomator/releases/download/1.19.0/cryptomator-1.19.0-aarch64.AppImage.asc
    checksum: 3198965add9b6f01952572a0a5be46602f117ac4a3a7d638b3bb057b50f637e7
    requiredOS: ""
  android:
    version: 1.11.1
    filename: Cryptomator-1.11.1.apk
    downloadUrl: https://static.cryptomator.org/android/1.11.1/Cryptomator-1.11.1.apk
    checksum: cd779e929277920e65b282f166e9c693fe560927215428796e100bcc7427132a
    requiredOS: Android 8.0
