baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en_US"
  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de_DE"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@skymatic/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

  [[module.mounts]]
    source = "node_modules/js-yaml/dist"
    target = "assets/js/js-yaml"

  [[module.mounts]]
    source = "node_modules/altcha/dist_external"
    target = "assets/js/altcha"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2-x64.exe"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.exe"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.exe.asc"
      checksum = "8fe76f4b14c771bc9f7134e3b4a4cbe0a1cf529107dd4c2d85900b0cb942433e"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.msi]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2-x64.msi"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.msi"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.msi.asc"
      checksum = "a000059df6e3ae628667d4b97c7639a3b5551916e63c0e356a39859741396fd2"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.dmg]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.dmg.asc"
      checksum = "9b4381a1310d76f8e6045756d66ade80e8519122dc3ea7a9065881c345c54b91"
      requiredOS = 'macOS 11'
    [params.releases.dmg-arm64]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2-arm64.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-arm64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-arm64.dmg.asc"
      checksum = "2a000a96bb310c8ee47a392eb4e005dd06eb437335dc97ad922d5b00120a1f01"
      requiredOS = 'macOS 11'
    [params.releases.appimage]
      version = "1.15.2"
      filename = "cryptomator-1.15.2-x86_64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/cryptomator-1.15.2-x86_64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/cryptomator-1.15.2-x86_64.AppImage.asc"
      checksum = "c43e752656bbb833f215f8443a385fb6408a2dc2436d0f5a919c2f5fd24626b4"
      requiredOS = ''
    [params.releases.appimage-aarch64]
      version = "1.15.2"
      filename = "cryptomator-1.15.2-aarch64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/cryptomator-1.15.2-aarch64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/cryptomator-1.15.2-aarch64.AppImage.asc"
      checksum = "12790e2a4e10eba8f352c68a40cb34d53bef91685bf49a42a0f18357e8e983e9"
      requiredOS = ''
    [params.releases.android]
      version = "1.11.1"
      filename = "Cryptomator-1.11.1.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.11.1/Cryptomator-1.11.1.apk"
      checksum = "cd779e929277920e65b282f166e9c693fe560927215428796e100bcc7427132a"
      requiredOS = 'Android 8.0'

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[server]
  [[server.headers]]
      for = '/**'
      [server.headers.values]
        Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-eval' https://umami.skymatic.de/ https://community.cryptomator.org/ https://js.stripe.com/ https://*.paddle.com/; style-src 'self' 'unsafe-inline' https://*.paddle.com/; img-src 'self' data: https://static.cryptomator.org/ https://*.paddle.com/ https://paddle.s3.amazonaws.com/; connect-src 'self' https://api.cryptomator.org/ https://store.cryptomator.org/ https://umami.skymatic.de/ http://localhost/ http://localhost:8787/; font-src 'self'; media-src https://static.cryptomator.org/; frame-src https://community.cryptomator.org/ https://js.stripe.com/ https://*.paddle.com/; base-uri 'self'; form-action 'self' https://www.paypal.com/ https://www.coinpayments.net/; frame-ancestors 'none';"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains"
        X-Content-Type-Options = "nosniff"
