baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en_US"
  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de_DE"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@skymatic/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

  [[module.mounts]]
    source = "node_modules/js-yaml/dist"
    target = "assets/js/js-yaml"

  [[module.mounts]]
    source = "node_modules/altcha/dist_external"
    target = "assets/js/altcha"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2-x64.exe"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.exe"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.exe.asc"
      checksum = "3cc0b786fe99923969a03f3829c378db3fe3d284baf90ddc2f15221d08f83f38"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.msi]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2-x64.msi"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.msi"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.msi.asc"
      checksum = "d97a3aa93b1a7eebbd1e0918e4a92a584c1adeae382baec98dccf2abfbfce45a"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.dmg]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-x64.dmg.asc"
      checksum = "36cfd2cd906071940e6684af596d8f4ab70a2faa6bd7459f184f99296538558b"
      requiredOS = 'macOS 11'
    [params.releases.dmg-arm64]
      version = "1.15.2"
      filename = "Cryptomator-1.15.2-arm64.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-arm64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.2/Cryptomator-1.15.2-arm64.dmg.asc"
      checksum = "21c4586179482e09a681d75b681b324698272ac5b961d641e7c105d2afd40db8"
      requiredOS = 'macOS 11'
    [params.releases.appimage]
      version = "1.15.3"
      filename = "cryptomator-1.15.3-x86_64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.3/cryptomator-1.15.3-x86_64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.3/cryptomator-1.15.3-x86_64.AppImage.asc"
      checksum = "5b95260e940e9c579577de66a436aa1fea4c559b42f391c632e9703287af45ee"
      requiredOS = ''
    [params.releases.appimage-aarch64]
      version = "1.15.3"
      filename = "cryptomator-1.15.3-aarch64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.3/cryptomator-1.15.3-aarch64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.15.3/cryptomator-1.15.3-aarch64.AppImage.asc"
      checksum = "2ac9df55a30718ab4c5a9d9fd5e4db65de2cf0890620e6e866e95ab84a24ac2a"
      requiredOS = ''
    [params.releases.android]
      version = "1.11.1"
      filename = "Cryptomator-1.11.1.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.11.1/Cryptomator-1.11.1.apk"
      checksum = "cd779e929277920e65b282f166e9c693fe560927215428796e100bcc7427132a"
      requiredOS = 'Android 8.0'

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[server]
  [[server.headers]]
      for = '/**'
      [server.headers.values]
        Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-eval' https://umami.skymatic.de/ https://community.cryptomator.org/ https://js.stripe.com/ https://*.paddle.com/; style-src 'self' 'unsafe-inline' https://*.paddle.com/; img-src 'self' data: https://static.cryptomator.org/ https://*.paddle.com/ https://paddle.s3.amazonaws.com/; connect-src 'self' https://api.cryptomator.org/ https://store.cryptomator.org/ https://umami.skymatic.de/ http://localhost/ http://localhost:8787/; font-src 'self'; media-src https://static.cryptomator.org/; frame-src https://community.cryptomator.org/ https://js.stripe.com/ https://*.paddle.com/; base-uri 'self'; form-action 'self' https://www.paypal.com/ https://www.coinpayments.net/; frame-ancestors 'none';"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains"
        X-Content-Type-Options = "nosniff"
