baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en_US"
  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de_DE"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@skymatic/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

  [[module.mounts]]
    source = "node_modules/js-yaml/dist"
    target = "assets/js/js-yaml"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.14.0"
      filename = "Cryptomator-1.14.0-x64.exe"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/Cryptomator-1.14.0-x64.exe"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/Cryptomator-1.14.0-x64.exe.asc"
      checksum = "6d87a1383a30c4b19664883732545970e83e08e33d28d68fb345bb2d79d162ba"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.msi]
      version = "1.14.0"
      filename = "Cryptomator-1.14.0-x64.msi"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/Cryptomator-1.14.0-x64.msi"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/Cryptomator-1.14.0-x64.msi.asc"
      checksum = "998b02c07f9df2bb661aee2c571be458a64c981da01e50d1857a6f7b892d67e4"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.dmg]
      version = "1.14.1"
      filename = "Cryptomator-1.14.1.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.1/Cryptomator-1.14.1-x64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.1/Cryptomator-1.14.1-x64.dmg.asc"
      checksum = "966e67cb1ad4e9a4d6ad49a36ed147f9d4c070fa48aa1001cd1a981dc06f17ff"
      requiredOS = 'macOS 11'
    [params.releases.dmg-arm64]
      version = "1.14.1"
      filename = "Cryptomator-1.14.1-arm64.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.1/Cryptomator-1.14.1-arm64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.1/Cryptomator-1.14.1-arm64.dmg.asc"
      checksum = "33663c07fda973a3ff17cb6113b7b28e08e42514506faec5e8fa8bcf24157746"
      requiredOS = 'macOS 11'
    [params.releases.appimage]
      version = "1.14.0"
      filename = "cryptomator-1.14.0-x86_64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/cryptomator-1.14.0-x86_64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/cryptomator-1.14.0-x86_64.AppImage.asc"
      checksum = "75441a3b68dead7974b04ff312006421faa33c528c4f627b69f4b6f883548ffc"
      requiredOS = ''
    [params.releases.appimage-aarch64]
      version = "1.14.0"
      filename = "cryptomator-1.14.0-aarch64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/cryptomator-1.14.0-aarch64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.0/cryptomator-1.14.0-aarch64.AppImage.asc"
      checksum = "c3eebf773d026387bf96f4540299a8fce382dca349ade225c96e8f80f2a5e92c"
      requiredOS = ''
    [params.releases.android]
      version = "1.10.2"
      filename = "Cryptomator-1.10.2.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.10.2/Cryptomator-1.10.2.apk"
      checksum = "7ac9fadd5da11740732fae34652e19f1cd31450dc2eb4b55ddfb9e52fd8be151"
      requiredOS = 'Android 8.0'

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[server]
  [[server.headers]]
      for = '/**'
      [server.headers.values]
        Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-eval' https://community.cryptomator.org/ https://js.stripe.com/ https://*.paddle.com/ https://www.google.com/ https://www.gstatic.com/; style-src 'self' 'unsafe-inline' https://*.paddle.com/; img-src 'self' data: https://static.cryptomator.org/ https://i.ytimg.com/ https://*.paddle.com/ https://paddle.s3.amazonaws.com/; connect-src 'self' https://api.cryptomator.org/ https://store.cryptomator.org/ http://localhost:8787/; font-src 'self'; media-src https://static.cryptomator.org/; frame-src https://community.cryptomator.org/ https://www.youtube-nocookie.com/ https://js.stripe.com/ https://*.paddle.com/ https://www.google.com/; base-uri 'self'; form-action 'self' https://www.paypal.com/ https://www.coinpayments.net/; frame-ancestors 'none'"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains"
        X-Content-Type-Options = "nosniff"
