baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en_US"
  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de_DE"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@skymatic/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

  [[module.mounts]]
    source = "node_modules/js-yaml/dist"
    target = "assets/js/js-yaml"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.14.2"
      filename = "Cryptomator-1.14.2-x64.exe"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-x64.exe"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-x64.exe.asc"
      checksum = "1d33841928f89669a2bdcc1a6e00ceb9b2b27ec6683463751ed1c708e781a99c"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.msi]
      version = "1.14.2"
      filename = "Cryptomator-1.14.2-x64.msi"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-x64.msi"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-x64.msi.asc"
      checksum = "521f49f22f2c3f4722c2a5ef5e069b673b73963ecbe576b2f13687eb687b2d56"
      requiredOS = 'Windows 10, Version 1803'
    [params.releases.dmg]
      version = "1.14.2"
      filename = "Cryptomator-1.14.2.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-x64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-x64.dmg.asc"
      checksum = "dea670a4cd9b2f55cc3608a564f6ea55cbbb6625b8d63dd88a6095b970052685"
      requiredOS = 'macOS 11'
    [params.releases.dmg-arm64]
      version = "1.14.2"
      filename = "Cryptomator-1.14.2-arm64.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-arm64.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/Cryptomator-1.14.2-arm64.dmg.asc"
      checksum = "73de6201a7502705d8cbf36ebd3d642b37fae9be73c230e9c2edd3a85cca7324"
      requiredOS = 'macOS 11'
    [params.releases.appimage]
      version = "1.14.2"
      filename = "cryptomator-1.14.2-x86_64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/cryptomator-1.14.2-x86_64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/cryptomator-1.14.2-x86_64.AppImage.asc"
      checksum = "ab819b4da5f8ec165ff2072266a4767c2ca781043c4e40efd001f8fc09cf31a1"
      requiredOS = ''
    [params.releases.appimage-aarch64]
      version = "1.14.2"
      filename = "cryptomator-1.14.2-aarch64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/cryptomator-1.14.2-aarch64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.14.2/cryptomator-1.14.2-aarch64.AppImage.asc"
      checksum = "f7447a3728098b415645fe56e2cc1f2866017fa95181b26d164a847d976c446d"
      requiredOS = ''
    [params.releases.android]
      version = "1.10.4"
      filename = "Cryptomator-1.10.4.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.10.4/Cryptomator-1.10.4.apk"
      checksum = "3b874ffa818b039bef06f0296cc7049aed5feba4f841308d80ec907aa28ca4b1"
      requiredOS = 'Android 8.0'

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[server]
  [[server.headers]]
      for = '/**'
      [server.headers.values]
        Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-eval' https://plausible.skymatic.de/ https://community.cryptomator.org/ https://js.stripe.com/ https://*.paddle.com/ https://www.google.com/ https://www.gstatic.com/; style-src 'self' 'unsafe-inline' https://*.paddle.com/; img-src 'self' data: https://static.cryptomator.org/ https://*.paddle.com/ https://paddle.s3.amazonaws.com/; connect-src 'self' https://api.cryptomator.org/ https://store.cryptomator.org/ https://plausible.skymatic.de/ http://localhost:8787/; font-src 'self'; media-src https://static.cryptomator.org/; frame-src https://community.cryptomator.org/ https://js.stripe.com/ https://*.paddle.com/ https://www.google.com/; base-uri 'self'; form-action 'self' https://www.paypal.com/ https://www.coinpayments.net/; frame-ancestors 'none'"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains"
        X-Content-Type-Options = "nosniff"
