baseApiUrl = "http://api.cryptomator.org"
storeApiUrl = "https://store.cryptomator.org/api"

umamiWebsiteId = "8d451e39-ffb2-4697-82c9-9f69eff497f1"

paddleEnableSandbox = false
paddleDesktopProductIds = [840163, 840164, 840165]
paddleAndroidProductId = 578277
paddleVendorId = 39223
paddleHubSelfHostedSubscriptionPlanId = 770132
paddleHubManagedSubscriptionPlanId = 807339
paddlePricesUrl = "https://checkout.paddle.com/api/2.0/prices"

stripePk = "pk_live_eSasX216vGvC26GdbVwA011V"

[stripePlans]
EUR = "plan_GgW4ovr7c6upzx"
USD = "plan_GejOEdJtfL3kdH"
