# API
apiBaseUrl: https://api.cryptomator.org
legacyApiUrl: http://api.cryptomator.org
legacyStoreUrl: https://store.cryptomator.org/api

# UMAMI
umamiWebsiteId: 8d451e39-ffb2-4697-82c9-9f69eff497f1

# PADDLE
paddleEnableSandbox: false
paddleToken: live_0af4126c5788dcda805e8389b96
paddleDesktopPriceIds: 
  - pri_01jb23tj1jxp88jt6yphast6th
  - pri_01jb23w0s2c2j3jebwtr5htwzj
  - pri_01jb23wh9vjqdskxyz96zhc4yk
paddleAndroidPriceId: pri_01jb2432chrz583xtxb029g40m
paddleVendorId: 39223
paddleHubSelfHostedSubscriptionPlanId: 770132
paddleHubManagedSubscriptionPlanId: 807339
paddlePricesUrl: https://checkout.paddle.com/api/2.0/prices

# STRIPE
stripePk: pk_live_eSasX216vGvC26GdbVwA011V
stripePlans:
  EUR: plan_GgW4ovr7c6upzx
  USD: plan_GejOEdJtfL3kdH
