name: Updates download urls to latest version

on:
  repository_dispatch:
    types: [desktop-update]

jobs:
  create-pr:
    name: Create PR for aur repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DESKTOP_VERSION: ${{ github.event.client_payload.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create new branch
        run: |
          git config --global safe.directory '*'
          git checkout -b "feature/desktop-${DESKTOP_VERSION}"
      - name: Update params.yaml
        run: |
           echo "TODO $DESKTOP_VERSION" > config/_default/params.yaml
      - name: Commit and push
        run: |
          git config user.name "cryptobot"
          git config user.email "cryptobot@users.noreply.github.com"
          git config push.autoSetupRemote true
          git stage config/_default/params.yaml
          git commit -m "Update desktop download urls to release ${DESKTOP_VERSION}"
          git push
      - name: Create pull request
        id: create-pr
        run: |
          printf "Created by $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" > pr_body.md
          PR_URL=$(gh pr create --title "Desktop release ${DESKTOP_VERSION}" --body-file pr_body.md)
          echo "url=$PR_URL" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.CRYPTOBOT_PR_TOKEN }}
      - name: Slack Notification
        if: github.event_name == 'release'
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CRYPTOMATOR_DESKTOP }}
          SLACK_USERNAME: 'Cryptobot'
          SLACK_ICON: false
          SLACK_ICON_EMOJI: ':bot:'
          SLACK_CHANNEL: 'cryptomator-desktop'
          SLACK_TITLE: "Website update PR created for release ${{ github.event.client_payload.version }} ."
          SLACK_MESSAGE: "See <${{ steps.create-pr.outputs.url }}|PR> on how to proceed."
          SLACK_FOOTER: false
          MSG_MINIMAL: true
